nginx:
  build: .
  ports:
    - "80:80"
    - "443:443"
    - "2222:22"
  links:
    - fpm:fpm
    - postgresql:postgresql
    - memcached:memcached
    - redis:redis
    - elasticsearch:elasticsearch
  volumes:
    - /mnt/www/php-dockerized/www:/var/www
    - /mnt/www/php-dockerized/sites:/etc/nginx/conf.d
    - /mnt/www/php-dockerized/logs:/var/log/supervisor


fpm:
  build: fpm
  ports:
    - "9000:9000"
  volumes:
    - /mnt/www/php-dockerized/www:/var/www

postgresql:
  image: postgres
  ports:
    - "5432:5432"

memcached:
  image: memcached
  ports:
    - "11211:11211"

redis:
  image: redis
  ports:
    - "6379:6379"

elasticsearch:
  image: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
